### ISSUE TITLE
swc/jest does not respect target option

### ISSUE THREAD

**Issue by egilsster** [swc-project/jest#48]
## Summary 

Trying to migrate a big suite from `babel-jest` to `@swc/jest` and hitting an issue with how it transpiles functions.

I created a reproduction repo here https://github.com/egilsster/swc-jest-issue

Essentially, I expect it to not transpile an arrow function to a regular function. I have `target` set to `es2015` but it acts the same with all future targets.

### Expected

Arrow function should be printed as `() => {}`

### Actual

- `@swc/jest` prints it as: `function() {}`
- `babel-jest` prints it as: `() => {}`

**Comment by kdy1** [comment]
How did you set target?
Using `.swcrc`?

**Comment by kdy1** [comment]
If you used `.swcrc`, it will be now fixed by https://github.com/swc-project/jest/commit/1900e6af14d450661fe181c95195517aa8aa9dc9

**Comment by egilsster** [comment]
I updated swc/jest to the new version you published (`0.2.10`) but it didn't fix it. I also inlined the config to isolate the issue further, still failing. https://github.com/egilsster/swc-jest-issue/runs/4340852709?check_suite_focus=true

**Comment by kdy1** [comment]
@egilsster I can't access the repository you shared

**Comment by egilsster** [comment]
Sorry, forgot to make it public, done!

**Comment by kdy1** [comment]
Ah, I forgot about https://github.com/swc-project/swc/issues/1108
Can you try target = es2016?

**Comment by egilsster** [comment]
Yeah it actually works with target set to `es2016` now that I both have your fix / have swcrc inlined so it gets the correct config.

Then I assume it is going to be resolved with https://github.com/swc-project/swc/issues/1108. If that's a correct assumption you can close this issue and I will keep track of the SWC issue.

**Comment by egilsster** [comment]
Closing this as it turned out to be an swc issue. Another part of the issue was in swc/jest but that was fixed (see kdy's comment above)
